baseURL = "https://es.shoogle.net/pais-vasco/"
languageCode = "es"
title = "País Vasco"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "pais-vasco"

[taxonomies]
  shop = "shops"

